Algoritmo "Quest03"

Var

      numeroFolhas, numeroCopias: real
Inicio
      escreval("Saiba quanto irá custar suas cópias...")
      escreval("**************************************")
      escreva("Quantas folhas do livro serão copiadas?  ")
      leia(numeroFolhas)
      numeroCopias <- numeroFolhas * 2
      escreval("")
      escreval("O total a pagar é de R$",numeroCopias*0.08)

Fimalgoritmo
