Algoritmo "Quest07"

Var

      nome: caractere
      km, hora, velMedia: real
Inicio

         escreva("Nome do piloto: ")
         leia(nome)
         escreval("")
         escreva("Informe a distância percorrida em Km: ")
         leia(km)
         escreval("")
         escreva("Informe o tempo percorrido em HORAS: ")
         leia(hora)
         escreval("")
         velMedia <- (km / hora)
 escreval("A velocidade média do piloto ", nome," foi ", velMedia," km/h")
         
Fimalgoritmo